# .goreleaser.yml
# Build customization
builds:
  binary: akamai-netstorage
  ldflags: -s -w
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
archive:
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ end }}"
  replacements:
    darwin: mac
  format: binary
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
release:
  draft: true
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}"
changelog:
  filters:
    exclude:
      - '^typo'
      - 'version bump'
